### ISSUE TITLE
Bundle with spa applications

### ISSUE THREAD

**Issue by at15** [arrowrowe/tam#3] opened 2015-10-11 15:24 UTC
I am working on a web project using java + javascript. I used to use freemarker as server side template , though most templates are html partials wrapped in angularjs. I want to remove all the template from server side and make it pure spa. So it would be a good idea to make `tam` work with some template build tools and generate all the html.

**Comment by arrowrowe** [comment] 2015-10-11 15:54
Is this a duplicate of #2?...

**Comment by at15** [comment] 2015-10-11 15:58
@arrowrowe part of, but there are some difference, you run a build command to add all the `script` and `link` tags in your html. But when bundle with php frameworks, you may read the json when the page is requested and add the tags dynamically instead of run a build command and change the php view files.
since for spa application, load everything at one time is a better option.

**Comment by arrowrowe** [comment] 2015-10-13 09:02
Am I right as following:
- A tool resolving #2 generates `link` and `script` tags when requested.
-  A tool resolving #3 writes the tags into html files.

**Comment by arrowrowe** [comment] 2015-10-30 15:54
I've got a simple sample... Gonna write a new npm package for this feature.

```html
<html>
<head>
  <title>arrowrowe</title>
  <link rel="icon" type="image/png" href="./logo.png">
  <link rel="stylesheet" href="@tam/core">
</head>
<body>
<script src="@tam/core"></script>
</body>
</html>
```

```javascript
var replace = require('gulp-replace');
var fs = require('fs-extra');

var getLinked = function () {
  return fs.readJsonSync('./linked.json');
};

var writeTamToHTML = function () {

  var linked = getLinked();
  var getBySuffix = function (pkg, suffix) {
    var suffixIndex = -suffix.length;
    return linked[pkg].filter(function (file) { return file.substr(suffixIndex) === suffix; });
  };
  var ReplaceToHTML = function (suffix) {
    return function (content, sBefore, pkg, sAfter) {
      return getBySuffix(pkg, suffix).map(function (file) { return sBefore + file + sAfter; }).join('');
    };
  };

  gulp.src(['./src/index.html'])
    .pipe(replace(/(<link .*?href=")@tam\/(.+?)(".*?>)/g, ReplaceToHTML('.css')))
    .pipe(replace(/(<script .*?src=")@tam\/(.+?)(".*?><\/script>)/g, ReplaceToHTML('.js')))
    .pipe(gulp.dest('./'));

};
```

**Comment by at15** [comment] 2015-10-30 16:59
@arrowrowe :+1: though I think there are already some packages in grunt and gulp for replace/render html files when build. Maybe we can use those packages directly instead of create a new one

**Comment by arrowrowe** [comment] 2015-11-01 13:50
We can use [TamHTML](https://github.com/arrowrowe/tam-html) now.

Sample: [arrowrowe/arrowrowe.github.io](https://github.com/arrowrowe/arrowrowe.github.io/).

Note [gulpfile.js](https://github.com/arrowrowe/arrowrowe.github.io/blob/dev/gulpfile.js) and `.plugins['tam-html']` in [assets.json](https://github.com/arrowrowe/arrowrowe.github.io/blob/dev/assets.json).

**Closed** 2015-11-01 13:50 UTC
